{-# LANGUAGE OverloadedStrings #-}

module Bio.Rosalind.PROT where

rnaToAminoAcids :: String -> String
rnaToAminoAcids [] = []
rnaToAminoAcids (x:y:z:t) | start `elem` ["UAA", "UAG", "UGA"] = []
                          | otherwise  = rnaToAminoAcid [x, y, z] : rnaToAminoAcids t
  where
    start = [x, y, z]                        
rnaToAminoAcids _ = error "This should not be happened"

rnaToAminoAcid :: String -> Char
rnaToAminoAcid "UUU" = 'F'
rnaToAminoAcid "UUC" = 'F'
rnaToAminoAcid "UUA" = 'L'
rnaToAminoAcid "UUG" = 'L'
rnaToAminoAcid "UCU" = 'S'
rnaToAminoAcid "UCU" = 'S'
rnaToAminoAcid "UUU" = 'F'      
rnaToAminoAcid "UUC" = 'F'      
rnaToAminoAcid "UUA" = 'L'      
rnaToAminoAcid "UUG" = 'L'      
rnaToAminoAcid "UCU" = 'S'      
rnaToAminoAcid "UCC" = 'S'      
rnaToAminoAcid "UCA" = 'S'      
rnaToAminoAcid "UCG" = 'S'      
rnaToAminoAcid "UAU" = 'Y'      
rnaToAminoAcid "UAC" = 'Y'      
rnaToAminoAcid "UAA" = '*'   
rnaToAminoAcid "UAG" = '*'   
rnaToAminoAcid "UGU" = 'C'      
rnaToAminoAcid "UGC" = 'C'      
rnaToAminoAcid "UGA" = '*'   
rnaToAminoAcid "UGG" = 'W'       
rnaToAminoAcid "CUU" = 'L'      
rnaToAminoAcid "CUC" = 'L'      
rnaToAminoAcid "CUA" = 'L'      
rnaToAminoAcid "CUG" = 'L'      
rnaToAminoAcid "CCU" = 'P'      
rnaToAminoAcid "CCC" = 'P'      
rnaToAminoAcid "CCA" = 'P'      
rnaToAminoAcid "CCG" = 'P'      
rnaToAminoAcid "CAU" = 'H'      
rnaToAminoAcid "CAC" = 'H'      
rnaToAminoAcid "CAA" = 'Q'      
rnaToAminoAcid "CAG" = 'Q'      
rnaToAminoAcid "CGU" = 'R'      
rnaToAminoAcid "CGC" = 'R'      
rnaToAminoAcid "CGA" = 'R'      
rnaToAminoAcid "CGG" = 'R'      
rnaToAminoAcid "AUU" = 'I'      
rnaToAminoAcid "AUC" = 'I'      
rnaToAminoAcid "AUA" = 'I'      
rnaToAminoAcid "AUG" = 'M'      
rnaToAminoAcid "ACU" = 'T'      
rnaToAminoAcid "ACC" = 'T'      
rnaToAminoAcid "ACA" = 'T'      
rnaToAminoAcid "ACG" = 'T'      
rnaToAminoAcid "AAU" = 'N'      
rnaToAminoAcid "AAC" = 'N'      
rnaToAminoAcid "AAA" = 'K'      
rnaToAminoAcid "AAG" = 'K'      
rnaToAminoAcid "AGU" = 'S'      
rnaToAminoAcid "AGC" = 'S'      
rnaToAminoAcid "AGA" = 'R'      
rnaToAminoAcid "AGG" = 'R'      
rnaToAminoAcid "GUU" = 'V'
rnaToAminoAcid "GUC" = 'V'
rnaToAminoAcid "GUA" = 'V'
rnaToAminoAcid "GUG" = 'V'
rnaToAminoAcid "GCU" = 'A'
rnaToAminoAcid "GCC" = 'A'
rnaToAminoAcid "GCA" = 'A'
rnaToAminoAcid "GCG" = 'A'
rnaToAminoAcid "GAU" = 'D'
rnaToAminoAcid "GAC" = 'D'
rnaToAminoAcid "GAA" = 'E'
rnaToAminoAcid "GAG" = 'E'
rnaToAminoAcid "GGU" = 'G'
rnaToAminoAcid "GGC" = 'G'
rnaToAminoAcid "GGA" = 'G'
rnaToAminoAcid "GGG" = 'G'
rnaToAminoAcid _     =  error "Could not translate"
